apiVersion: v1
kind: Service
metadata:
  name: jenkinsprac-service
  labels:
    app: jenkinsprac-app
spec:
  selector:
    app: jenkinsprac-app
  type: LoadBalancer
  ports:
  - nodePort: 32751
    port: 8080
    targetPort: 8080
